// Central include for the URnetwork SDK C++ wrapper plus shared process
// bootstrap (log dir, memory limit). The wrapper (urnetwork_sdk.hpp) is
// generated by sdk/cgo and vendored under third_party/urnetwork-sdk/include;
// it is the app-facing API (RAII handles, typed structs, std::function
// callbacks). URnetworkSdk.dll is linked via its generated import library.
//
// SPDX-License-Identifier: MPL-2.0
#pragma once

#include <urnetwork_sdk.hpp>

namespace urnw {

// Initialize the SDK for this process: point glog at the per-process log dir and
// set the process memory budget. Call once at startup, before constructing any
// NetworkSpace/Device. memoryLimitBytes matches the macOS caps (app ~64MB,
// service 48-64MB); the service is intentionally memory-bounded.
void SdkInit(bool isService, int64_t memoryLimitBytes);

}  // namespace urnw
