// The two byte formats the update checker must never get wrong, parsed pure.
//
// Both sit on the trust boundary between "downloaded from the release" and
// "about to touch the running installation", which is why they live here as
// header-only pure functions rather than inline in the checker: the service
// selftest exercises exactly the code the app will run, the same arrangement
// VersionGrammar.h already has for the tag grammar.
//
//   Sha256ForFile        finds a file's expected hash in a SHA256SUMS document
//                        (`sha256sum` format: 64 hex chars, two-character
//                        separator, filename). A lookup that "almost" matches —
//                        wrong file, malformed hex — must come back empty, not
//                        close, because the caller compares it against a hash
//                        it computed itself and empty can never accidentally
//                        equal anything.
//   IsAllowedPayloadName the zip-slip defence's allowlist. Archive entry paths
//                        are NEVER trusted: after extraction the checker takes
//                        only top-level files whose bare names pass this test
//                        (the exe/dll/pri payload) and ignores everything else,
//                        so a hostile archive member named `..\evil.exe` or
//                        `C:\x.dll` cannot become a swap target even if the
//                        extractor were to misbehave.
//
// No Windows headers, no allocation beyond the returned string, total on all
// inputs.
//
// SPDX-License-Identifier: MPL-2.0
#pragma once

#include <string>
#include <string_view>

namespace urnw::update {

namespace format_detail {

inline constexpr bool IsHexDigit(char c) noexcept {
  return (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') ||
         (c >= 'A' && c <= 'F');
}

inline constexpr char AsciiLower(char c) noexcept {
  return (c >= 'A' && c <= 'Z') ? static_cast<char>(c - 'A' + 'a') : c;
}

}  // namespace format_detail

// True when the two strings are equal under ASCII case folding. Enough for the
// two uses here — hex digits and Windows file extensions — and deliberately not
// a general Unicode casefold, which neither needs.
inline constexpr bool EqualsAsciiCaseless(std::string_view a,
                                          std::string_view b) noexcept {
  if (a.size() != b.size()) return false;
  for (std::size_t i = 0; i < a.size(); ++i) {
    if (format_detail::AsciiLower(a[i]) != format_detail::AsciiLower(b[i]))
      return false;
  }
  return true;
}

// The lowercase SHA-256 hex for `fileName` in a SHA256SUMS document, or empty
// when no well-formed line names it. Line format is sha256sum's:
//
//   <64 hex chars><space><space or *><filename>\n
//
// (space = text mode, * = binary mode; the release pipeline writes the
// two-space form, but a document regenerated by hand with `sha256sum -b` must
// not stop verifying). CR line endings are tolerated because the document may
// have been written on Windows. The FILENAME comparison is exact — release
// asset names are minted by our own pipeline in known case — but the HEX is
// canonicalized to lowercase so the caller can compare it against its own
// formatting without a second folding step.
inline std::string Sha256ForFile(std::string_view sums,
                                 std::string_view fileName) {
  while (!sums.empty()) {
    const std::size_t eol = sums.find('\n');
    std::string_view line =
        sums.substr(0, eol == std::string_view::npos ? sums.size() : eol);
    sums.remove_prefix(eol == std::string_view::npos ? sums.size() : eol + 1);
    if (!line.empty() && line.back() == '\r') line.remove_suffix(1);

    // 64 hex + 2 separator chars + at least 1 name char.
    if (line.size() < 67) continue;
    bool hexOk = true;
    for (std::size_t i = 0; i < 64 && hexOk; ++i)
      hexOk = format_detail::IsHexDigit(line[i]);
    if (!hexOk || line[64] != ' ') continue;
    if (line[65] != ' ' && line[65] != '*') continue;
    if (line.substr(66) != fileName) continue;

    std::string hex;
    hex.reserve(64);
    for (std::size_t i = 0; i < 64; ++i)
      hex.push_back(format_detail::AsciiLower(line[i]));
    return hex;
  }
  return {};
}

// Whether an extracted file's bare name is one the swap may touch: a single
// path component (no separators, no drive colon, not a dot name) whose
// extension is .exe, .dll or .pri — the payload classes the portable zip's
// root actually carries. Assets in subdirectories are outside the swap on
// purpose; see the checker for what that costs and why it is the right trade.
inline bool IsAllowedPayloadName(std::string_view name) noexcept {
  if (name.empty() || name == "." || name == "..") return false;
  for (char c : name) {
    if (c == '/' || c == '\\' || c == ':') return false;
  }
  const std::size_t dot = name.rfind('.');
  if (dot == std::string_view::npos || dot == 0) return false;  // no empty stem
  const std::string_view ext = name.substr(dot);
  return EqualsAsciiCaseless(ext, ".exe") || EqualsAsciiCaseless(ext, ".dll") ||
         EqualsAsciiCaseless(ext, ".pri");
}

}  // namespace urnw::update
